#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jide-app
  labels:
    app: jide-app
spec:
 replicas: 3
 selector:
   matchLabels:
     app: jide-app
 template:
   metadata:
     labels:
       app: jide-app
   spec:
     containers:
     - name: coach-con
       image: mobanntechnologies/jan24:17
       ports:
       - containerPort: 8080

---
#Service Type nodePort
apiVersion: v1
kind: Service
metadata:
  name: jide-app
  labels:
    app: jide-app
spec:
  selector:
    app: jide-app
  type: NodePort
  ports:
  - nodePort: 32005
    port: 8080
    targetPort: 8080

